home=`pwd`
download=${home}/download
cluster=${home}/cluster
RED='\033[0;31m'
NC='\033[0m' # No Color
jdk_path=$cluster/jdk
hadoop_path=$cluster/hadoop
scala_path=$cluster/scala
spark_path=$cluster/spark
stb_path=$cluster/sbt
master_file=$home/master
slave_file=$home/slaves 
user=gb305058
